### ISSUE TITLE
`exec format error` when running `dx/start`

### ISSUE THREAD

**Issue by moritztim** [davetron5000/declare-ai.org#2]
I tried to run this by following the README instructions and got this error:
```console
 > [app 2/4] RUN apt-get -y update:
0.490 exec /bin/sh: exec format error
```
Here's the full output:
```console
[ dx/start ] ✅ dx/docker-compose.env is up to date
[ dx/start ] 🚀 Starting docker-compose.dx.yml
[+] Building 2.3s (6/8)                                                                             docker:default
 => [app internal] load build definition from Dockerfile.dx                                                   0.1s
 => => transferring dockerfile: 360B                                                                          0.0s
 => [app internal] load metadata for docker.io/library/node:20.5                                              1.2s
 => [app internal] load .dockerignore                                                                         0.1s
 => => transferring context: 2B                                                                               0.0s
 => [app internal] load build context                                                                         0.1s
 => => transferring context: 86B                                                                              0.0s
 => CACHED [app 1/4] FROM docker.io/library/node:20.5@sha256:8d9887b3b05d2e65598a18616c37cfc271346d12248dfcb  0.0s
 => ERROR [app 2/4] RUN apt-get -y update                                                                     0.6s
------                                                                                                             
 > [app 2/4] RUN apt-get -y update:
0.490 exec /bin/sh: exec format error
------
failed to solve: process "/bin/sh -c apt-get -y update" did not complete successfully: exit code: 255
```

**Comment by davetron5000** [comment]
I think this happens when an image is a different architecture than the computer running Docker.  Can you try removing 

```yaml
    platform: ${DOCKER_DEFAULT_PLATFORM}
```

from the `docker-compose.dx.yml` and see if that fixes it for you? I *think* specifying the platform like the file has isn't needed, but since this works on my Apple Silicon computer I can't easily check.

**Comment by moritztim** [comment]
That didn't work. However changing it to `linux/amd64` did work for some reason, however, I'm now getting the error at serve
```console
[ dx/exec ] 🚂 Running 'bin/serve' inside container with service name 'app'
exec bin/serve: exec format error
```
So I modified the `.env` files to say `linux/amd64`, which didn't help.

**Comment by davetron5000** [comment]
I wonder if there is a still a non-AMD64 thing lying around.  Can you try:

`node -v`

if that doesn't work, you'll need to rebuild your image (* below)

If running `node` **does** work, could be something native in `node_modules`. try `rm -rf node_modules ; bin/setup` then see if it works.

(I'm seeing that I checked in some arm64 configuration I should not have, so I will look into removing that)

**Comment by davetron5000** [comment]
* `dx/prune` should remove all images and containers and force a fresh rebuild

**Comment by davetron5000** [comment]
Also, you can try #6 which should have prevented the issues you are having.

If `dx/prune` doesn't work, you can `docker container ls` and anything for declare-ai, you can `docker container rm «id»`, then repeat for `docker image ls` and `docker image rm`.

Sorry for all the trouble!

**Comment by moritztim** [comment]
> Sorry for all the trouble!

Don't worry, I don't mind at all

Host info:
- node version: `v23.1.0
- Processor: Intel x64
- (I use arch btw)

Here's what I did now
1. delete node_modules
2. change platform in both `.env` files
3. remove image and container
4. `dx/start`, which worked.
5. `dx/exec bin/setup && dx/exec bin/build && dx/exec bin/serve`, which got me the same error as before.

**Comment by moritztim** [comment]
> Also, you can try https://github.com/davetron5000/declare-ai.org/pull/6 which should have prevented the issues you are having.

Should have? This isn't merged, let me try

**Comment by davetron5000** [comment]
"should have" as in if I had done it that way the first time

**Comment by moritztim** [comment]
Oh, I see. Well, I repeated steps 1 and 3 - 5 with the same results, while having checked out the pr.

**Comment by davetron5000** [comment]
This is surprising, since there isn't anything platform specific - I'm wondering if something bad is cached somewhere.

Can you try changing `dx/docker-compose.env` (on the branch) so that `IMAGE` and `PROJECT_NAME` are different values?  This should hopefully prevent any re-use.  you could also get drastic and delete all images or at least those created in the last e.g. 24 hours?

**Comment by moritztim** [comment]
It works now, following the instructions in the readme of #6

**Comment by davetron5000** [comment]
whew!  Thanks for keeping with it
