### ISSUE TITLE
"Generative AI" or "generative AI"

### ISSUE THREAD

**Issue by moritztim** [davetron5000/declare-ai.org#3]
Currently most files capitalize the "G", but some don't.
![generative AI search results](https://github.com/user-attachments/assets/2629821e-a463-478f-b07d-5e37512f5059)
![Generative AI search results](https://github.com/user-attachments/assets/81107a71-f5ee-4d2a-b6aa-20f92e32ef23)
I believe that it should be lowercase, because "Generative AI" isn't a name in my opinion, just a regular word and an abbreviation.

**Comment by davetron5000** [comment]
Idea was that `Generative AI` was titleized to call back to the definition.  But it should be consistent either way. I will noodle on this and either clarify titlization or make it lower case.

**Comment by moritztim** [comment]
I see where you're coming from but wouldn't it be lowercase when used in a sentence tho, since it isn't a title then?

**Comment by davetron5000** [comment]
Agreed with your assessment and should be in sentence case wherever appropriate (modulo any typos I made changing things :)
