### ISSUE TITLE
Open Discussions

### ISSUE THREAD

**Issue by moritztim** [davetron5000/declare-ai.org#8]
Just one more: could you enable discussions on this repo, so grand plans like mine can be stowed away there, next to links to automation tools, deliberation on semantic details and questions about edgecases?

**Comment by davetron5000** [comment]
Yes! Thanks for the engagement. I had updates to this way down on my TODO list, but I will process what you've posted here this weekend and come back with some ideas for moving forward next week

**Comment by moritztim** [comment]
Thanks so much for having a look! And for creating this in the first place, I'm really glad it exists. And there's need to hurry at all.

**Comment by davetron5000** [comment]
Done, however I realized I had not added a code of conduct, so that has been added.
